linters:
  enable-all: true
  disable:
    - golint
    - deadcode
    - structcheck
    - exhaustivestruct
    - maligned
    - interfacer
    - varcheck
    - nosnakecase
    - scopelint
    - ifshort
